name: LLM News Daily

on:
  schedule:
    - cron: '15 13 * * *'  # 13:15 UTC -> 20:15 Asia/Bangkok (adjust as needed)
  workflow_dispatch:
    inputs:
      run_once:
        description: 'Run pipeline immediately'
        required: false
        default: 'true'

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
            python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run pipeline
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          NASA_API_KEY: ${{ secrets.NASA_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          ENABLE_ARXIV: 'true'
          ENABLE_CROSSREF: 'true'
          ENABLE_GOOGLE_SCHOLAR: 'false'
          ENABLE_NASA: 'true'
          ENABLE_TECH_NEWS: 'true'
          MAX_PAPERS_PER_DAY: '6'
          SUMMARY_MIN_LENGTH: '120'
          SUMMARY_MAX_LENGTH: '260'
          MIN_NEWS_QUOTA: '2'
          LOG_LEVEL: 'INFO'
          TIMEZONE: 'Asia/Bangkok'
        run: |
          python app.py --run-once

      - name: Upload logs artifact (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: llm-news-logs
          path: logs
          if-no-files-found: ignore
